Sistema_OE/Sistema_OE/Controllers/MateriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using Sistema_OE.Models;

namespace Sistema_OE.Controllers
{
    public class MateriaController : Controller
    {
        #region Variables Globales
        private const int RegistrosPorPagina = 8; // Define la constante para la cantidad de registros por página

        #endregion

        #region BD
        private readonly SistemaOeContext _dbContext;

        public MateriaController(SistemaOeContext context)
        {
            _dbContext = context;
        }
        #endregion

        #region  Mostrar, Index
        // GET: Materia
        public async Task<IActionResult> Index(int PagActual = 0)
        {
            try
            {
                SqlParameter totalPag = new SqlParameter("@TotalPag", System.Data.SqlDbType.Int);
                totalPag.Direction = System.Data.ParameterDirection.Output;

                var materia = await _dbContext.Materia
                    .FromSqlRaw("EXEC paMostrarMateria @NPag, @CantReg, @palabraBusc, @TotalPag OUTPUT",
                        new SqlParameter("@NPag", PagActual),
                        new SqlParameter("@CantReg", RegistrosPorPagina), // Cantidad de registros por página
                        new SqlParameter("@palabraBusc", ""),
                        totalPag)
                    .ToListAsync();

                int totalPages = Convert.ToInt32(totalPag.Value);

                ViewBag.PagActual = PagActual + 1;
                ViewBag.totalPag = totalPages; // Total de veces que puede tocar el botón
                // Crear un objeto IPagedList<Administrativo> para la vista
                var materiaPaged = new StaticPagedList<Materium>(materia, PagActual + 1, 10, totalPages * 10);

                return View(materiaPaged);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Problem("An error occurred while retrieving data.");
            }


        }
        #endregion

        #region Buscar
        public JsonResult Buscar(string searchTerm, int PagActual = 0)
        {
            try
            {
                //var pageSize = 1; // Cambia esto según tus necesidades
                //var pageNumber = page ?? 1;

                SqlParameter totalPag = new SqlParameter("@TotalPag", System.Data.SqlDbType.Int);
                totalPag.Direction = System.Data.ParameterDirection.Output;

                var materia = _dbContext.Materia
                    .FromSqlRaw("EXEC paMostrarMateria @NPag, @CantReg, @palabraBusc, @TotalPag OUTPUT",
                        new SqlParameter("@NPag", PagActual), // Ajustar el índice de página
                        new SqlParameter("@CantReg", RegistrosPorPagina),
                        new SqlParameter("@palabraBusc", searchTerm),
                        totalPag)
                    .ToList();

                int totalPages = Convert.ToInt32(totalPag.Value);

                ViewBag.PagActual = PagActual + 1;
                ViewBag.totalPag = totalPages; // Total de veces que puede tocar el botón
                // Crear un objeto IPagedList<Administrativo> para la vista
                var materiaPaged = new StaticPagedList<Materium>(materia, PagActual + 1, 10, totalPages * 10);


                return Json(new { Materia = materiaPaged, PagActual = PagActual + 1, TotalPaginas = totalPages });
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json(new { Error = "An error occurred while retrieving data." });
            }
        }
        #endregion

        #region Crear
        [HttpPost]
        public JsonResult CrearMateria([FromBody] Materium materium)
        {
            try
            {
                SqlParameter msjParam = new SqlParameter("@msj", System.Data.SqlDbType.VarChar, 40);
                msjParam.Direction = System.Data.ParameterDirection.Output;

                SqlParameter seAgregoParam = new SqlParameter("@seAgrego", System.Data.SqlDbType.TinyInt);
                seAgregoParam.Direction = System.Data.ParameterDirection.Output;

                _dbContext.Database.ExecuteSqlRaw("EXEC paCrearMateria @nombre, @msj OUTPUT, @seAgrego OUTPUT",
                    new SqlParameter("@nombre", materium.Nombre),
                    msjParam,
                    seAgregoParam
                );

                string? v = msjParam.Value.ToString();
                byte seAgrego = Convert.ToByte(seAgregoParam.Value);

                return Json(new { status = seAgrego, mensaje = v });
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return Json(new { status = 0, mensaje = "Error en el servidor" });
            }
        }
        #endregion

        #region Obtener Mat
        public JsonResult GetMateria(int id, bool verId)
        {
            try
            {
                var materia = _dbContext.Materia
                    .FromSqlRaw("EXEC paBuscarUnMat @p0, @p1", id, verId)
                    .ToList(); // Ejecuta la consulta y obtiene los resultados

                if (materia.Count > 0)
                {
                    return Json(materia.First()); // Devuelve el primer administrador encontrado
                }
                else
                {
                    return Json(null); // Devuelve null si no se encontró ningún administrador
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json(new { error = ex.Message });
            }
        }
        #endregion

        #region Editar
        [HttpPost]
        public JsonResult ActualizarMateria(int id, [FromBody] Materium materia)
        {
            try
            {
                SqlParameter outputMessage = new SqlParameter("@msj", System.Data.SqlDbType.VarChar, 40)
                {
                    Direction = System.Data.ParameterDirection.Output
                };

                SqlParameter outputModified = new SqlParameter("@seModifico", System.Data.SqlDbType.TinyInt)
                {
                    Direction = System.Data.ParameterDirection.Output
                };

                _dbContext.Database.ExecuteSqlRaw("EXEC paActualizarMateria @numMateria, @nombre, @msj output, @seModifico output",
                    new SqlParameter("@numMateria", id),
                    new SqlParameter("@nombre", materia.Nombre),
                    
                    outputMessage,
                    outputModified);

                string? v = outputMessage.Value.ToString();
                int seModifico = Convert.ToInt32(outputModified.Value);

                return Json(new { status = seModifico, mensaje = v });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json(new { status = 0, mensaje = "Error en la actualización la materia" });
            }

        }
        #endregion


        #region Eliminar
        [HttpPost]
        public JsonResult EliminarMateria(int id)
        {
            try
            {
                SqlParameter outputMessage = new SqlParameter("@msj", System.Data.SqlDbType.VarChar, 40)
                {
                    Direction = System.Data.ParameterDirection.Output
                };

                SqlParameter outputDeleted = new SqlParameter("@seElimino", System.Data.SqlDbType.TinyInt)
                {
                    Direction = System.Data.ParameterDirection.Output
                };

                _dbContext.Database.ExecuteSqlRaw("EXEC paEliminarMateria @numMateria, @msj output, @seElimino output",
                    new SqlParameter("@numMateria", id),
                    outputMessage,
                    outputDeleted);

                string? v = outputMessage.Value.ToString();
                int seElimino = Convert.ToInt32(outputDeleted.Value);

                return Json(new { status = seElimino, mensaje = v });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json(new { status = 0, mensaje = "Error al eliminar la materia" });
            }
        }
        #endregion  

        #region getMateria
        public JsonResult GetEstudiantes()
        {
            try
            {
                var materias = _dbContext.Set<Estudiante>()
             .FromSqlRaw("SELECT * FROM  fnListaEstudiante()")
             .ToList();

                return Json(materias);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json(new { error = ex.Message });
            }
        }
        #endregion 

        #region asignar materia
        [HttpPost]
        public async Task<IActionResult> AsignarEstudiante([FromBody] Estudianteseccionanio estudianteAsignada)
        {
            try
            {
                var estudianteCedulaParam = new SqlParameter("@estudianteCedula", estudianteAsignada.CedulaEstudiante);
                var numMateriaParam = new SqlParameter("@numMateria", estudianteAsignada.NumSeccion);

                await _dbContext.Database.ExecuteSqlRawAsync("EXEC sp_AsignarEst @estudianteCedula, @numSeccion", estudianteCedulaParam, numMateriaParam);

                return Json(new { success = true, message = "Estudiante asignada con éxito." });
            }
            catch (Exception ex)
            {
                // Aquí puedes manejar el error. Por ejemplo, podrías registrar el error en tus logs.
                Console.WriteLine(ex.Message);

                return Json(new { success = false, message = ex.Message });
            }
        }
        #endregion 

    }




}

Sistema_OE/Sistema_OE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  - Sistema_OE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* noelia<link rel="stylesheet" href="~/SOE.styles.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/js/site.js" />
    <!-- CSS de Bootstrap (agrega el enlace correcto si estás usando una versión específica) -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- Agrega el enlace al archivo de estilos CSS de SweetAlert -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.css">
    <!-- Agrega el enlace al archivo de JavaScript de highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css">

    <link href="~/css/styles.css" rel="stylesheet" />

    <!-- esto fue lo que le agregue para el carrucel-->

   <!-- codigo de prueba noe-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Libraries Stylesheet -->
    <link href="~/lib/bootstrap/animate.min.css" rel="stylesheet">
    <link href="~/css/myStyle.css" rel="stylesheet">
    <link href="~/css/myStyleTwo.css" rel="stylesheet"> 
    <!-- fin codigo de prueba noe-->
    

</head>
<body>

    <div class="d-flex" id="wrapper" >
        <!-- Sidebar-->
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light" >SistemaOE</div>
            <div class="list-group list-group-flush" >
                <sidebar >
                    <ul>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INICIO</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Administrador" asp-action="Index">Administradores</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Materia" asp-action="Index">Materia</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Seccions" asp-action="Index">Sección</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Profesor" asp-action="Index">Profesor</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiante</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Expediente" asp-action="Index">Expediente</a></li>
                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Equipointerdiciplinarios" asp-action="Index">Equipo</a></li>
                     
                    </ul>
                </sidebar>

            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" >
                <div class="container-fluid">
                    <!-- le agrege esto nuevo-->
                    <i class="bi bi-justify">
                        <button class="btn" id="sidebarToggle" style="background-color: #009688">
                            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-justify" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M2 12.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </button>
                    </i>
                </div>
            </nav>

            <div class="right_col x f" id="renderBody" role="main">

                @RenderBody()

            </div>
            @*             <footer>
            <div class="pull-right">
            SOE
            </div>
            <div class="clearfix"></div>
            </footer> *@

        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> 

    @await RenderSectionAsync("Scripts", required: false)

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <!-- esto fue lo que le agregue para el carrucel-->
</body>
</html>